workflows:
  android-build:
      name: Build Android APK
          environment:
                android:
                        sdk: 34
                            scripts:
                                  - name: Install Build Tools 34.0.0
                                          script: |
                                                    yes | sdkmanager "build-tools;34.0.0"
                                                          - name: Get Dependencies
                                                                  script: |
                                                                            flutter pub get
                                                                                  - name: Build APK (not AAB)
                                                                                          script: |
                                                                                                    flutter build apk --release
                                                                                                        artifacts:
                                                                                                              - build/app/outputs/flutter-apk/app-release.apk
